### ISSUE TITLE
STDIN  Defaults

### ISSUE THREAD

**Issue by wpromatt** [jakm/msgpack-cli#1]
Might be nice if it defaulted to read from stdin and output to stdout for unix piping.

**Comment by jakm** [comment]
Hi,
you can use standard Linux devices /dev/stdin and /dev/stdout for pipelining. Is it acceptable for you?
Jakub

**Comment by jakm** [comment]
Like this:
`echo -n '{"name": "foo", "number": 42}' | msgpack-cli encode /dev/stdin | msgpack-cli decode /dev/stdin --pp`

**Comment by wpromatt** [comment]
Yeah, was just thinking a default would be nice.

**Comment by jakm** [comment]
Default read from stdin was added by PR #3
