### ISSUE TITLE
Fails to decode valid msgpack file

### ISSUE THREAD

**Issue by enkore** [jakm/msgpack-cli#2]
The file causing the problem: [167.bin.zip](https://github.com/ugorji/go/files/430828/167.bin.zip) (zipped because GitHub doesn't allow .bin attachments)

What msgpack-python does with it:

``` py
>>> import msgpack
>>> msgpack.load(open('167.bin', 'rb'))
{b'version': 2, b'segments': {19: 1}, b'compact': {19: 164}}
```

What msgpack-cli does with it:

``` console
$ msgpack-cli decode 167.bin
2016/08/22 20:04:58 [pos 11]: readContainerLen: Unrecognized descriptor byte: hex: 13, decimal: 19
zsh: exit 1     msgpack-cli decode 167.bin
```

SHA-256:

``` console
$ sha256sum 167.bin
f559290e95be95e56ec8f956382d1a29b50b0fd8d4baa806e3b4892a144acefb  167.bin
```

Hexdump

```
00000000  83 a7 63 6f 6d 70 61 63  74 81 13 cc a4 a8 73 65  |..compact.....se|
00000010  67 6d 65 6e 74 73 81 13  01 a7 76 65 72 73 69 6f  |gments....versio|
00000020  6e 02                                             |n.|
00000022
```

([Previous bug report at ugorji/go](https://github.com/ugorji/go/issues/167))

**Comment by jakm** [comment]
The reason why you can't decode this file is that it is not encodable to json. Json objects allow only string keys, so I use mapping to map[string]interface{} for all objects.
